[project]
name = "GFrbmg2"
description = "A project for background removal using GFrbmg2 and BEN2 models"
version = "1.0.0"
license = { text = "MIT" }
dependencies = [
    "einops>=0.3.0",
    "timm>=0.4.12",
    "Pillow>=8.4.0",
]

[project.urls]
Repository = "https://github.com/gorillaframeai/GF_nodes"

[tool.comfy]
PublisherId = "GorillaFrame"
DisplayName = "GF Remove Background 2.0"
Icon = "ğŸµ"