[project]
name = "RMBG-2.0"
description = "ğŸµ GF Remove Background 2.0"
version = "1.2"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/gorillaframeai/GF_nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "GorillaFrame"
DisplayName = "GF"
Icon = "ğŸµ"
